import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import GraphInitializer from "./GraphInitializer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* The small client component that loads the graph globally once */}
      <GraphInitializer />
      {/* Then render the rest of the app */}
      <body className={inter.className}>{children}</body>
    </html>
  );
}
